stages:
- name: Build
  steps:
  - publishImageConfig:
      dockerfilePath: ./images/7.2/Dockerfile
      buildContext: ../images/7.2/
      tag: jde5011/multisite-php
      pushRemote: true
      registry: index.docker.io
timeout: 60
